use_frameworks!
platform :ios, '12.0'
target 'ReactiveARKit_Example' do
  pod 'ReactiveARKit', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'ReactiveARKit_Tests' do
    inherit! :search_paths

    
  end
end
